// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHdmJ4m3-X_19H8OsXDyVmWk9OD0feHgo',
    appId: '1:1059940068463:web:96b14e63d4f940293fb19a',
    messagingSenderId: '1059940068463',
    projectId: 'aspireedge-100da',
    authDomain: 'aspireedge-100da.firebaseapp.com',
    storageBucket: 'aspireedge-100da.firebasestorage.app',
    measurementId: 'G-RJDYR3W30H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8N4FAHvX30_ekvTDVBZ-TPEuZV3TqZU',
    appId: '1:1059940068463:android:caa10ef55e8ada083fb19a',
    messagingSenderId: '1059940068463',
    projectId: 'aspireedge-100da',
    storageBucket: 'aspireedge-100da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr88K-39C_k0F6qO0gxBaiKU-B5WV7RRE',
    appId: '1:1059940068463:ios:ec6f23f23e01b6e73fb19a',
    messagingSenderId: '1059940068463',
    projectId: 'aspireedge-100da',
    storageBucket: 'aspireedge-100da.firebasestorage.app',
    iosBundleId: 'com.example.aspireEdge',
  );
}
